"""Winding-fraction mechanism audit: triangle phase-class asym is
generated by winding-fraction N-trend with lattice-constant bin-asyms.

Hypothesis from comprehensive audit (2026-05-02):
  bin1 (winding +1): asym_bin1 = +0.254 (lattice constant)
  bin2 (winding 0 + winding -1): asym_bin2 = -0.021 (lattice constant)
  all-asym = f_bin1 * asym_bin1 + (1-f_bin1) * asym_bin2

If this two-bin model is correct, the all-asym N-trend reduces to the
N-trend of f_bin1 (winding-+1 fraction). Symanzik-fit f_bin1(N) -> asymptote
determines the asym_inf.

Per regime, per seed:
  - count triangles by winding (+1, 0, -1) using SIGNED wilson_red sign
    (after projecting principal-sum mod 2pi to (-pi, pi])
  - measure asym_bin1, asym_bin2 to verify they're truly lattice-constant
  - extract f_bin1, f_bin2

Output: outputs/audit_winding_fraction_mechanism.json
"""
from __future__ import annotations
import json
import sys
from collections import defaultdict
from pathlib import Path

import numpy as np

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / "src"))
PARENT = REPO.parent

LADDER = [
    ("P5N64",  64,  "results_d1_p5n64_24seeds/P5N64.snapshots.npz"),
    ("P5N72",  72,  "results_d1_p5n72_24seeds/P5N72.snapshots.npz"),
    ("P5N84",  84,  "results_d1_p5n84_24seeds/P5N84.snapshots.npz"),
    ("P5N100",100,  "results_d1_p5n100_24seeds/P5N100.snapshots.npz"),
    ("P5N128",128,  "results_d1_p5n128_kq_fixed/P5N128.snapshots.npz"),
    ("P5N200",200,  "results_d1_p5n200_8seeds/P5N200.snapshots.npz"),
    ("P5N256",256,  "results_d1_p5n256_12seeds/P5N256.snapshots.npz"),
    ("P5N300",300,  "results_d1_p5n300_12seeds/P5N300.snapshots.npz"),
    ("P5N512", 512,  "results_d1_p5n512_12seeds/P5N512.snapshots.npz"),
]


def find_persistent_triangles(pers_edges):
    edge_set = set()
    for a, b in pers_edges:
        a, b = int(a), int(b)
        if a == b:
            continue
        edge_set.add((min(a, b), max(a, b)))
    adj = defaultdict(set)
    for a, b in edge_set:
        adj[a].add(b)
        adj[b].add(a)
    triangles = []
    for (i, j) in edge_set:
        common = adj[i] & adj[j]
        for k in common:
            if k <= j:
                continue
            triangles.append((i, j, k))
    return triangles


def winding_classification(triangles, psi_last):
    """Pure sign-based winding bin: principal-sum sign, NOT magnitude.
    Floating-point sign of (d_ij+d_jk+d_ki) is the physical signal —
    correlates with PPN vs PNN classification.
    """
    if not triangles:
        return [], []
    phi = np.angle(psi_last)
    classifications = []
    wilson_values = []
    for i, j, k in triangles:
        d_ij = np.angle(np.exp(1j * (phi[j] - phi[i])))
        d_jk = np.angle(np.exp(1j * (phi[k] - phi[j])))
        d_ki = np.angle(np.exp(1j * (phi[i] - phi[k])))
        if abs(d_ij) < 1e-9 or abs(d_jk) < 1e-9 or abs(d_ki) < 1e-9:
            continue
        n_pos = ((1 if d_ij > 0 else 0) + (1 if d_jk > 0 else 0)
                  + (1 if d_ki > 0 else 0))
        if n_pos == 3:
            tri_class = "PPP"
        elif n_pos == 2:
            tri_class = "PPN"
        elif n_pos == 1:
            tri_class = "PNN"
        else:
            tri_class = "NNN"
        wilson_principal_sum = d_ij + d_jk + d_ki
        # Use the principal-sum DIRECTLY (NOT mod 2pi) — its sign is
        # the relevant observable
        if wilson_principal_sum < 0:
            winding_bin = "neg"
        else:
            winding_bin = "pos"
        classifications.append((winding_bin, tri_class))
        wilson_values.append(wilson_principal_sum)
    return classifications, wilson_values


def per_seed_winding_stats(xi_traj, psi_last, n_lat):
    d_xi = np.abs(np.diff(xi_traj, axis=0))
    offdiag = ~np.eye(n_lat, dtype=bool)
    d_off = d_xi[:, offdiag]
    v_med = (float(np.median(d_off[d_off > 0]))
              if (d_off > 0).any() else 1e-6)
    c_info = 2 * v_med
    persistent_mask_off = (d_off > c_info).mean(axis=0) > 0.5
    ij_idx = np.argwhere(offdiag)
    pers_edges = ij_idx[persistent_mask_off]
    triangles = find_persistent_triangles(pers_edges)
    classifications, wilson_values = winding_classification(
        triangles, psi_last)
    if not classifications:
        return None
    counts = defaultdict(int)
    for wb, tc in classifications:
        counts[(wb, tc)] += 1
    n_total = len(classifications)
    n_pos = sum(1 for w, _ in classifications if w == "pos")
    n_neg = sum(1 for w, _ in classifications if w == "neg")
    n_zero = sum(1 for w, _ in classifications if w == "zero")
    # Asym in each winding bin
    def asym(bin_name):
        n_PPN = counts.get((bin_name, "PPN"), 0)
        n_PNN = counts.get((bin_name, "PNN"), 0)
        if n_PPN + n_PNN == 0:
            return float("nan"), 0
        return (n_PPN - n_PNN) / (n_PPN + n_PNN), n_PPN + n_PNN
    asym_pos, n_pos_class = asym("pos")
    asym_neg, n_neg_class = asym("neg")
    asym_zero, n_zero_class = asym("zero")
    n_PPN_all = sum(counts.get((wb, "PPN"), 0)
                      for wb in ("pos", "neg", "zero"))
    n_PNN_all = sum(counts.get((wb, "PNN"), 0)
                      for wb in ("pos", "neg", "zero"))
    asym_all = ((n_PPN_all - n_PNN_all) / (n_PPN_all + n_PNN_all)
                 if n_PPN_all + n_PNN_all > 0 else float("nan"))
    return {
        "n_triangles_total": n_total,
        "n_winding_pos": n_pos, "n_winding_neg": n_neg,
        "n_winding_zero": n_zero,
        "frac_winding_neg": n_neg / max(n_total, 1),
        "frac_winding_pos": n_pos / max(n_total, 1),
        "frac_winding_zero": n_zero / max(n_total, 1),
        "asym_winding_neg": asym_neg, "n_class_neg": n_neg_class,
        "asym_winding_pos": asym_pos, "n_class_pos": n_pos_class,
        "asym_winding_zero": asym_zero, "n_class_zero": n_zero_class,
        "asym_all": asym_all,
    }


def main():
    print("=" * 80)
    print("Winding-fraction mechanism audit")
    print("=" * 80)
    print()
    rows = []
    for regime, n_lat, rel in LADDER:
        fp = PARENT / rel
        if not fp.exists():
            continue
        z = np.load(fp, allow_pickle=True)
        snaps = z["edge_xi_snapshots"]
        psi_r = z["psi_real_snapshots"]
        psi_i = z["psi_imag_snapshots"]
        n_seeds = int(snaps.shape[0])
        per_seed = []
        for s in range(n_seeds):
            xi_traj = np.asarray(snaps[s], dtype=float).copy()
            psi_last = (psi_r[s, -1].astype(float)
                        + 1j * psi_i[s, -1].astype(float))
            stats = per_seed_winding_stats(xi_traj, psi_last, n_lat)
            if stats is None:
                continue
            per_seed.append(stats)
        if not per_seed:
            continue
        def mn(key):
            vals = [d[key] for d in per_seed
                     if not (isinstance(d.get(key), float)
                              and np.isnan(d[key]))]
            return float(np.mean(vals)) if vals else float("nan")
        def std_unc(key):
            vals = [d[key] for d in per_seed
                     if not (isinstance(d.get(key), float)
                              and np.isnan(d[key]))]
            if len(vals) < 2:
                return float("nan")
            return float(np.std(vals)) / np.sqrt(len(vals))
        f_neg = mn("frac_winding_neg")
        f_pos = mn("frac_winding_pos")
        f_zero = mn("frac_winding_zero")
        a_neg = mn("asym_winding_neg")
        a_pos = mn("asym_winding_pos")
        a_zero = mn("asym_winding_zero")
        a_all = mn("asym_all")
        u_neg = std_unc("asym_winding_neg")
        u_pos = std_unc("asym_winding_pos")
        u_all = std_unc("asym_all")
        u_fneg = std_unc("frac_winding_neg")
        # Two-bin model prediction
        # asym_pred = f_neg * a_neg + f_pos * a_pos + f_zero * a_zero
        asym_pred = (f_neg * a_neg if not np.isnan(a_neg) else 0) \
                     + (f_pos * a_pos if not np.isnan(a_pos) else 0) \
                     + (f_zero * a_zero if not np.isnan(a_zero) else 0)
        print(f"--- {regime} N={n_lat} (n_seeds={len(per_seed)}) ---")
        print(f"  Winding fractions: neg={f_neg:.4f}+-{u_fneg:.4f}, "
              f"pos={f_pos:.4f}, zero={f_zero:.4f}")
        print(f"  Per-bin asym:")
        print(f"    neg: {a_neg:+.4f}+-{u_neg:.4f}  "
              f"pos: {a_pos:+.4f}+-{u_pos:.4f}  zero: {a_zero:+.4f}")
        print(f"  asym_all measured = {a_all:+.5f}+-{u_all:.5f}")
        print(f"  asym_all predicted (model) = {asym_pred:+.5f}")
        print(f"  diff (model - measured) = {asym_pred - a_all:+.5f}")
        rows.append({
            "regime": regime, "N": n_lat, "n_seeds": len(per_seed),
            "frac_winding_neg_mean": f_neg,
            "frac_winding_pos_mean": f_pos,
            "frac_winding_zero_mean": f_zero,
            "frac_winding_neg_unc": u_fneg,
            "asym_winding_neg_mean": a_neg,
            "asym_winding_pos_mean": a_pos,
            "asym_winding_zero_mean": a_zero,
            "asym_winding_neg_unc": u_neg,
            "asym_winding_pos_unc": u_pos,
            "asym_all_measured_mean": a_all,
            "asym_all_unc": u_all,
            "asym_all_predicted_two_bin_model": asym_pred,
            "model_minus_measured": asym_pred - a_all,
            "per_seed": per_seed,
        })
    print()
    print("=" * 80)
    print("Cross-regime synthesis + Symanzik fit on f_winding_neg")
    print("=" * 80)
    if rows:
        N_arr = np.array([r["N"] for r in rows], dtype=float)
        f_neg_arr = np.array([r["frac_winding_neg_mean"] for r in rows])
        f_neg_unc = np.array([r["frac_winding_neg_unc"] for r in rows])
        a_neg_arr = np.array([r["asym_winding_neg_mean"] for r in rows
                                if not np.isnan(r["asym_winding_neg_mean"])])
        a_pos_arr = np.array([r["asym_winding_pos_mean"] for r in rows
                                if not np.isnan(r["asym_winding_pos_mean"])])
        # Verify lattice-constancy of bin asyms
        print(f"  asym_winding_neg cross-regime: "
              f"{a_neg_arr.mean():+.4f} +/- {a_neg_arr.std():.4f}  "
              f"(if lattice-const should be near 0)")
        print(f"  asym_winding_pos cross-regime: "
              f"{a_pos_arr.mean():+.4f} +/- {a_pos_arr.std():.4f}")
        # Symanzik fit on f_neg
        x = 1.0 / N_arr
        w = 1.0 / np.maximum(f_neg_unc, 1e-6) ** 2
        A = np.column_stack([np.ones_like(x), x])
        AtWA = A.T @ (w[:, None] * A)
        AtWy = A.T @ (w * f_neg_arr)
        try:
            coef = np.linalg.solve(AtWA, AtWy)
            a_inf, b = coef
            cov = np.linalg.inv(AtWA)
            a_unc = float(np.sqrt(cov[0, 0]))
            b_unc = float(np.sqrt(cov[1, 1]))
            pred = A @ coef
            chi2 = float(np.sum(w * (f_neg_arr - pred) ** 2))
            dof = len(rows) - 2
            print()
            print(f"  Symanzik fit f_winding_neg = a + b/N:")
            print(f"    a (N->inf) = {a_inf:.5f} +/- {a_unc:.5f}")
            print(f"    b coef     = {b:+.4f} +/- {b_unc:.4f}")
            print(f"    chi2/dof   = {chi2:.2f}/{dof}")
            # Predicted asym_inf via two-bin model with lattice-const bin asyms
            a_neg_const = a_neg_arr.mean()
            a_pos_const = a_pos_arr.mean() if a_pos_arr.size else 0.0
            asym_inf_pred = (a_inf * a_neg_const
                              + (1 - a_inf) * a_pos_const)
            print(f"    Predicted asym_inf "
                  f"(two-bin model, asym_neg={a_neg_const:.4f}, "
                  f"asym_pos={a_pos_const:.4f}):")
            print(f"      asym_inf = {asym_inf_pred:+.5f}")
            print(f"      target -pi/200 = {-np.pi/200:+.5f}, "
                  f"diff = {asym_inf_pred - (-np.pi/200):+.5f}")
        except np.linalg.LinAlgError:
            print(f"  Fit failed (singular)")

    bundle = {
        "method": "winding_fraction_mechanism_audit",
        "rows": rows,
    }
    out = REPO / "outputs" / "audit_winding_fraction_mechanism.json"
    out.write_text(json.dumps(bundle, indent=2), encoding="utf-8")
    print(f"\nSaved {out}")


if __name__ == "__main__":
    main()
