r"""Auto-generate LaTeX rows for table tab:sg_ladder in P4 manuscript.

Reads outputs/derive_skeleton_weighted_lift_chain.json (which itself
auto-discovers the ladder via _d1_ladder_discovery), and emits a tex
snippet to paper/generated/sg_ladder_rows.tex that the manuscript
imports via \input{generated/sg_ladder_rows.tex}.

When a new high-N production lands (N=2048, 4096, ...), re-running
the derive_skeleton_weighted_lift_chain.py followed by this generator
automatically updates the manuscript table without manual edits.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

SRC = Path(__file__).resolve().parent
REPO = SRC.parent
OUTPUTS = REPO / "outputs"
GENERATED = REPO / "paper" / "generated"
GENERATED.mkdir(parents=True, exist_ok=True)


def emit_sg_ladder_rows() -> int:
    chain_json = OUTPUTS / "derive_skeleton_weighted_lift_chain.json"
    if not chain_json.is_file():
        print(f"  [error] {chain_json} missing; run derive_skeleton_weighted_lift_chain.py first")
        return 1

    bundle = json.loads(chain_json.read_text(encoding="utf-8"))
    rows = bundle["per_regime"]
    rows.sort(key=lambda r: r["N"])

    out_path = GENERATED / "sg_ladder_rows.tex"
    lines = [
        "% AUTO-GENERATED by src/generate_sg_ladder_tex.py from",
        "% outputs/derive_skeleton_weighted_lift_chain.json",
        "% DO NOT EDIT MANUALLY — re-run the generator after new N data.",
        "%",
    ]
    for r in rows:
        n = r["N"]
        seeds = r["n_seeds"]
        wm = r["weighted_l2"]
        sm = r["skeleton_l2"]
        lift = r["lift_l2"]
        # Format: N | seeds | weighted lambda_2 | skeleton lambda_2 | lift
        lines.append(
            f"{n:>5d} & {seeds:>3d} & "
            f"{wm:.4f} & {sm:.4f} & {lift:.4f} \\\\"
        )
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")

    # Also emit Symanzik asymptotes as a tex macro file
    sym = bundle["symanzik"]
    macros = GENERATED / "sg_asymptotes.tex"
    macros_lines = [
        "% AUTO-GENERATED Symanzik asymptotes for inclusion in P4 manuscript.",
        f"\\newcommand{{\\sgWeightedAsymptote}}{{{sym['weighted']['a_inf']:.5f}}}",
        f"\\newcommand{{\\sgWeightedRelErr}}{{{sym['weighted']['rel_err_pct']:+.2f}\\%}}",
        f"\\newcommand{{\\sgSkeletonAsymptote}}{{{sym['skeleton']['a_inf']:.5f}}}",
        f"\\newcommand{{\\sgSkeletonRelErr}}{{{sym['skeleton']['rel_err_pct']:+.2f}\\%}}",
        f"\\newcommand{{\\sgLiftAsymptote}}{{{sym['lift']['a_inf']:.5f}}}",
        f"\\newcommand{{\\sgLiftRelErr}}{{{sym['lift']['rel_err_pct']:+.2f}\\%}}",
        f"\\newcommand{{\\sgChainResidual}}{{{bundle['chain_reconstruction']['chain_residual_pct']:+.2f}\\%}}",
        f"\\newcommand{{\\sgNMax}}{{{rows[-1]['N']}}}",
        f"\\newcommand{{\\sgNRegimes}}{{{len(rows)}}}",
    ]
    macros.write_text("\n".join(macros_lines) + "\n", encoding="utf-8")

    print(f"Wrote: {out_path} ({len(rows)} rows)")
    print(f"Wrote: {macros}")
    return 0


if __name__ == "__main__":
    sys.exit(emit_sg_ladder_rows())
