r"""Adaptive carrier-pipeline orchestrator (CLI).

Runs the full Tier 1-4 stack on existing data:

  1. Auto-discover ladder via _d1_ladder_discovery
  2. Per-regime per-seed lambda_2 extraction
  3. Hierarchical Bayesian Symanzik fit (Tier 4)
  4. Model comparison: Symanzik-1 vs -2 vs -3 via Bayes factors
  5. Theory-hybrid prior over candidate rationals (Tier 4)
  6. Joint posterior P(lambda_inf = p/q | data) per rational
  7. Multi-closure joint posterior (Tier 4)
  8. Gittins-index ranked next-action recommendation (Tier 4)
  9. Bayesian stopping criterion check (Tier 1)

Output: outputs/adaptive_pipeline_report.json + console + tex macros.
"""
from __future__ import annotations

import json
import math
import sys
from fractions import Fraction
from pathlib import Path

import numpy as np

SRC = Path(__file__).resolve().parent
REPO = SRC.parent
OUTPUTS = REPO / "outputs"
OUTPUTS.mkdir(parents=True, exist_ok=True)
GENERATED = REPO / "paper" / "generated"
GENERATED.mkdir(parents=True, exist_ok=True)

sys.path.insert(0, str(SRC))
from _d1_ladder_discovery import discover_d1_ladder  # noqa: E402
from adaptive_pipeline import (
    theory_prior,
    hierarchical_bayes,
    seed_budget,
    bracket_check,
    bayesian_stopping,
    gittins,
    multi_closure,
)


def extract_per_seed_lambdas(ladder, tau: float = 0.10,
                                max_seeds_per_n: int = 8,
                                min_n: int = 100) -> tuple[np.ndarray, np.ndarray]:
    """Extract per-seed weighted lambda_2 from each ladder regime."""
    all_n = []
    all_lam = []
    for regime, n_lat, npz_path in ladder:
        if n_lat < min_n:
            continue
        d = np.load(npz_path, allow_pickle=True)
        if "edge_xi_snapshots" not in d.files:
            continue
        xi_arr = d["edge_xi_snapshots"][:, -1]
        n_seeds = min(max_seeds_per_n, xi_arr.shape[0])
        for s in range(n_seeds):
            xi = xi_arr[s].astype(np.float64)
            np.fill_diagonal(xi, 0.0)
            deg = np.maximum(xi.sum(axis=1), 1e-12)
            d_inv = 1.0 / np.sqrt(deg)
            laplacian = np.eye(xi.shape[0]) - (d_inv[:, None] * xi * d_inv[None, :])
            laplacian = 0.5 * (laplacian + laplacian.T)
            try:
                eigs = np.linalg.eigvalsh(laplacian)
                all_n.append(n_lat)
                all_lam.append(float(eigs[1]))  # lambda_2
            except np.linalg.LinAlgError:
                continue
    return np.asarray(all_n), np.asarray(all_lam)


def gaussian_likelihood_rational(p_q: Fraction, mu: float, sigma: float) -> float:
    """N(p/q; mu, sigma) likelihood."""
    z = (float(p_q) - mu) / max(sigma, 1e-12)
    return math.exp(-0.5 * z * z) / (sigma * math.sqrt(2.0 * math.pi))


def enumerate_simplest_rationals(q_max: int) -> list[Fraction]:
    seen = set()
    out = []
    for q in range(2, q_max + 1):
        for p in range(1, q):
            f = Fraction(p, q)
            if f.denominator > q_max:
                continue
            if f not in seen:
                seen.add(f)
                out.append(f)
    return out


def compute_posterior(mu: float, sigma: float, q_max: int = 50,
                       window: float | None = None) -> dict:
    """Theory-hybrid Bayesian posterior over rationals."""
    rationals = enumerate_simplest_rationals(q_max)
    if window is not None:
        rationals = [r for r in rationals if abs(float(r) - mu) <= window]
    prior_table = theory_prior.prior_table(rationals)
    posterior = {}
    for r in rationals:
        prior = prior_table[r]["prior"]
        likelihood = gaussian_likelihood_rational(r, mu, sigma)
        posterior[r] = prior * likelihood
    z = sum(posterior.values()) or 1.0
    return {r: p / z for r, p in posterior.items()}


def emit_tex_macros(report: dict):
    """Write paper/generated/adaptive_macros.tex with current posterior summary."""
    out_path = GENERATED / "adaptive_macros.tex"
    fit = report["hierarchical_fit"]
    top_post = report["posterior"]["top_rational"]
    top_p = report["posterior"]["top_posterior"]
    n_regimes_count = len(set([d["rational"] for d in report["posterior"]["top_10"]])) or 1
    # Count regimes used in fit (distinct N values in observations)
    n_regimes_used = report.get("n_regimes_in_fit", 0)
    lines = [
        "% AUTO-GENERATED by src/run_adaptive_pipeline.py",
        f"\\newcommand{{\\adaptiveAsymptote}}{{{fit['a_mean']:.5f}}}",
        f"\\newcommand{{\\adaptiveAsymptoteStd}}{{{fit['a_std']:.5f}}}",
        f"\\newcommand{{\\adaptiveTopRational}}{{{top_post}}}",
        f"\\newcommand{{\\adaptiveTopPosterior}}{{{top_p:.3f}}}",
        f"\\newcommand{{\\adaptiveModelSelected}}{{{fit['selected']}}}",
        f"\\newcommand{{\\adaptiveBayesFactorTwoVsOne}}"
        f"{{{report['model_comparison'].get('bayes_factor_2_vs_1', float('nan')):.3f}}}",
        f"\\newcommand{{\\adaptiveLadderNMax}}{{{report['ladder_n_max']}}}",
        f"\\newcommand{{\\adaptiveLadderNObs}}{{{report['n_observations']}}}",
        f"\\newcommand{{\\adaptiveLadderNRegimes}}{{{n_regimes_used}}}",
    ]
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main():
    print("=" * 78)
    print("Adaptive Carrier Pipeline — Tier 1-4 Integrated Analysis")
    print("=" * 78)

    # 1+2. Auto-discover + extract per-seed lambda_2
    ladder = discover_d1_ladder(REPO)
    print(f"\n  Discovered {len(ladder)} ladder regimes:")
    for regime, n, _ in ladder:
        print(f"    {regime} (N={n})")
    n_arr, lam_arr = extract_per_seed_lambdas(ladder)
    print(f"\n  Extracted {len(lam_arr)} per-seed observations "
          f"(N range {n_arr.min()}..{n_arr.max()})")

    # 3. Hierarchical Bayesian fit
    print("\n--- Hierarchical Bayesian Symanzik fit ---")
    cmp = hierarchical_bayes.model_comparison(n_arr, lam_arr)
    for k in ("symanzik_1", "symanzik_2", "symanzik_3"):
        if k in cmp:
            v = cmp[k]
            print(f"  {k}: a = {v['asymptote_mean']:.5f} +/- {v['asymptote_std']:.5f}, "
                  f"log_ev = {v['log_evidence']:+.2f}")
    print(f"  Bayes factor 2v1 = {cmp.get('bayes_factor_2_vs_1', float('nan')):.3f}")
    print(f"  Bayes factor 3v2 = {cmp.get('bayes_factor_3_vs_2', float('nan')):.3f}")
    print(f"  Selected: {cmp['selected']}")
    best = cmp[cmp["selected"]]
    fit_data = {
        "selected": cmp["selected"],
        "a_mean": best["asymptote_mean"],
        "a_std": best["asymptote_std"],
        "ci95": best["asymptote_ci95"],
        "sigma_seed": best["sigma_seed"],
    }

    # 4. Theory-hybrid Bayesian posterior
    print("\n--- Theory-hybrid Bayesian Rational Identification ---")
    mu = best["asymptote_mean"]
    sigma = best["asymptote_std"]
    posterior = compute_posterior(mu, sigma, q_max=50, window=10 * sigma)
    rows = sorted(posterior.items(), key=lambda kv: kv[1], reverse=True)
    print(f"  Asymptote: {mu:.5f} +/- {sigma:.5f}")
    print(f"  Top-10 posterior (Occam + theory anchors):")
    for r, p in rows[:10]:
        z = (float(r) - mu) / sigma
        print(f"    {r.numerator}/{r.denominator}  value={float(r):.5f}  "
              f"z={z:+.2f}  posterior={p:.5f}")

    top_rat, top_post = rows[0]
    posterior_summary = {
        "top_rational": f"{top_rat.numerator}/{top_rat.denominator}",
        "top_posterior": top_post,
        "second_rational": (f"{rows[1][0].numerator}/{rows[1][0].denominator}"
                              if len(rows) > 1 else ""),
        "second_posterior": rows[1][1] if len(rows) > 1 else 0.0,
        "posterior_odds": top_post / max(rows[1][1], 1e-12) if len(rows) > 1 else float("inf"),
    }

    # 5. Bayesian stopping check
    print("\n--- Bayesian Stopping Criterion ---")
    posterior_dict_str = {f"{r.numerator}/{r.denominator}": p for r, p in posterior.items()}
    stop, reason = bayesian_stopping.should_stop(posterior_dict_str, target_posterior=0.95)
    print(f"  Stop: {stop}, {reason}")
    entropy = bayesian_stopping.posterior_entropy_bits(posterior_dict_str)
    print(f"  Posterior entropy: {entropy:.3f} bits")

    # 6. Gittins-ranked next actions
    print("\n--- Gittins-Index Next-Action Ranking ---")
    actions = gittins.standard_action_menu(current_sigma=sigma)
    ranked = gittins.rank_actions(actions, sigma_prior=sigma)
    print("  Top-5 actions by info-per-compute:")
    for r in ranked[:5]:
        print(f"    [{r.rank}] {r.action.name}: "
              f"cost={r.action.cost_hours:.3f}h, "
              f"EIG={r.eig_bits:.3f} bits, Gittins={r.gittins_index:.2f} bits/h")

    # 7. Multi-closure joint posterior
    print("\n--- Multi-Closure Joint Posterior ---")
    samples = multi_closure.joint_posterior_sample(n_samples=10000)
    mc_summary = multi_closure.joint_summary(samples)
    for k, v in mc_summary.items():
        print(f"    {k}: {v['mean']:.5f} +/- {v['std']:.5f}  "
              f"vs registered {v['registered_rational_value']:.5f}  z={v['z_from_registered']:+.2f}")

    # Bundle report
    report = {
        "title": "Adaptive Carrier Pipeline — Tier 1-4 Integrated Analysis",
        "ladder_n_max": int(n_arr.max()),
        "n_observations": int(len(lam_arr)),
        "n_regimes_in_fit": len(set(n_arr.tolist())),
        "hierarchical_fit": fit_data,
        "model_comparison": {k: v for k, v in cmp.items()
                              if k in ("symanzik_1", "symanzik_2", "symanzik_3",
                                       "bayes_factor_2_vs_1", "bayes_factor_3_vs_2",
                                       "selected")},
        "posterior": {
            **posterior_summary,
            "top_10": [{"rational": f"{r.numerator}/{r.denominator}",
                          "value": float(r), "posterior": p}
                          for r, p in rows[:10]],
        },
        "stopping": {"should_stop": stop, "reason": reason,
                       "entropy_bits": entropy},
        "next_actions_top5": [
            {"name": r.action.name, "cost_hours": r.action.cost_hours,
              "eig_bits": r.eig_bits, "gittins_index": r.gittins_index,
              "rank": r.rank}
            for r in ranked[:5]
        ],
        "multi_closure": mc_summary,
    }

    out_path = OUTPUTS / "adaptive_pipeline_report.json"
    out_path.write_text(json.dumps(report, indent=2, default=str), encoding="utf-8")
    print(f"\nSaved: {out_path}")

    # Emit tex macros
    emit_tex_macros(report)
    print(f"Saved: {GENERATED / 'adaptive_macros.tex'}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
